# Generated by Django 3.1.5 on 2021-07-26 05:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 7, 26, 5, 25, 34, 211772, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
